// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.29.3

package fhv.ops.proto;

public final class Order {
  private Order() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 3,
      /* suffix= */ "",
      Order.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ProductOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ProductOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Receipt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Receipt_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\"6\n\023ProductOrderRequest\022\017\n\007" +
      "product\030\001 \001(\t\022\016\n\006amount\030\002 \001(\005\":\n\007Product" +
      "\022\014\n\004name\030\001 \001(\t\022\016\n\006amount\030\002 \001(\005\022\021\n\tunitPr" +
      "ice\030\003 \001(\001\"I\n\007Receipt\022\027\n\005items\030\001 \003(\0132\010.Pr" +
      "oduct\022\022\n\ntotalPrice\030\002 \001(\001\022\021\n\ttimestamp\030\003" +
      " \001(\00329\n\016OrderProcessor\022\'\n\005Order\022\024.Produc" +
      "tOrderRequest\032\010.ReceiptB\021\n\rfhv.ops.proto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ProductOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ProductOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_ProductOrderRequest_descriptor,
        new java.lang.String[] { "Product", "Amount", });
    internal_static_Product_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Product_descriptor,
        new java.lang.String[] { "Name", "Amount", "UnitPrice", });
    internal_static_Receipt_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Receipt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Receipt_descriptor,
        new java.lang.String[] { "Items", "TotalPrice", "Timestamp", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
