// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.29.3

package fhv.ops.proto;

public interface ProductOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ProductOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product = 1;</code>
   * @return The product.
   */
  java.lang.String getProduct();
  /**
   * <code>string product = 1;</code>
   * @return The bytes for product.
   */
  com.google.protobuf.ByteString
      getProductBytes();

  /**
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();
}
