// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: order.proto
// Protobuf Java Version: 4.29.3

package fhv.ops.proto;

public interface ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Product items = 1;</code>
   */
  java.util.List<fhv.ops.proto.Product> 
      getItemsList();
  /**
   * <code>repeated .Product items = 1;</code>
   */
  fhv.ops.proto.Product getItems(int index);
  /**
   * <code>repeated .Product items = 1;</code>
   */
  int getItemsCount();
  /**
   * <code>repeated .Product items = 1;</code>
   */
  java.util.List<? extends fhv.ops.proto.ProductOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <code>repeated .Product items = 1;</code>
   */
  fhv.ops.proto.ProductOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <code>double totalPrice = 2;</code>
   * @return The totalPrice.
   */
  double getTotalPrice();

  /**
   * <code>int64 timestamp = 3;</code>
   * @return The timestamp.
   */
  long getTimestamp();
}
